[package]
name = "a2s"
description = "Rust implementation of Source A2S query"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/rumblefrog/a2s-rs"
authors = ["rumblefrog <contact@zhenyangli.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
bzip2 = "0.3.3"
crc = "^1.0.0"
